kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-history-server-config
  namespace: ${spark_namespace}
data:
  spark-defaults.conf: |-
    spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.WebIdentityTokenCredentialsProvider
    spark.history.fs.eventLog.rolling.maxFilesToRetain=5